title: Holicamp
author: holicamp
email: hello@holicamp.org.uk
description: Holiday play-scheme camp for children
baseurl: ""
url: "https://holicamp.org.uk"
google_tag_manager: "UA-90339029-2"
recaptcha_site_key: "6LfTc1oaAAAAAN5amUOU-hbU8DHHKMek3ZaPOp0J"
formspree_id: "xnqoypoy"
prices:
  outdoor:
    day: 45
    week:
      5: 180
      4: 160
  indoor:
    day: 50
    week:
      5: 195
      4: 175

facebook_username: holicamplondon
instagram_username: holicamplondon

# disqus:
#   shortname: janczizikow # to enable comments replace with your_disqus_shortname

# Build settings
markdown: kramdown
highlighter: rouge # or pygments or null
exclude:
  - README.md
  - LICENSE.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js

include: ['_pages']
permalink: /:categories/:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
